language: rust
rust: stable
cache: cargo
sudo: false
git:
  depth: 1
addons:
  apt:
    packages:
      - g++-6
      - libstdc++6
before_install:
  - sudo apt-get

before_script:
  - |
      export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH &&
      ci/install-tools.sh
  - |
      ci/install-glslangValidator.sh
script:
  - ci/run-all.sh
after_success:
  - ci/upload-docs.sh
